### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by NoLooseEnds** [Shazman96/DCAStack#1]
This looks very interesting. 

Would love to have this as a docker image for easy deployment and self-hosting. 

Thanks!

**Comment by Shazman96** [comment]
Absolutely! I can work towards a dockerized version of this entire project.

**Comment by ChrisLAS** [comment]
Amazing! Looking forward to that! 

We run a few podcasts and I will spread the word to my community! 

Cheers, thanks for the great tool!
-Chris

**Comment by Shazman96** [comment]
Sorry for the delay, I had some issues getting Docker up and running. I've updated the README with a new section just for the self-hosters.

https://github.com/Shazman96/DCAStack#what-if-i-wanted-to-self-host

Please feel free to open a PR if you think you can optimize the Docker files! I'd love to learn from the community as well :)

**Comment by NoLooseEnds** [comment]
Great! Thanks for working on this.

I'm wondering why you have this:

```
python3 -m venv YOUR_ENV_NAME_HERE
source YOUR_ENV_NAME_HERE/bin/activate
cd REPO_NAME
pip install -r requirements.txt
python3 manage.py db init
```

Don't that defeat the purpose of docker? Why is this done in on the host and not in in docker.

**Comment by Shazman96** [comment]
Thank you for your questions!

> Great! Thanks for working on this.
> 
> I'm wondering why you have this:
> 
> ```
> python3 -m venv YOUR_ENV_NAME_HERE
> source YOUR_ENV_NAME_HERE/bin/activate
> cd REPO_NAME
> pip install -r requirements.txt
> python3 manage.py db init
> ```
> 
> Don't that defeat the purpose of docker? Why is this done in on the host and not in docker.

The reason I am doing that bit of ugly python code outside of docker and on the host venv is because we need that migrations folder to exist outside the docker environment. It creates a migrations folder that contains all my DB changes and modifications which needs to get tracked with git, used to build the production environment and production DBs. 

The way I have things setup is a bit wonky. I use docker for all my local development but deploy to heroku using a Procfile (see here: https://github.com/Shazman96/DCAStack/blob/main/Procfile).

> EDIT2: I'm not super experienced in Docker either, but I'm wondering why there different local and internal ports by default (i.e `5004:5000`). Why not just set it to `5000:5000` default, and let the user change it. Quite a few use some sort of "proxy" like traefik (or caddy) – and don't really expose ports.

I've made the modification to make the port `5000:5000` by default. Not sure why it was 5004 to begin with, must have fat fingered something. 

> Another thing, I think you could put some repeating things into a .env file for the docker-compose, like the redis-url for instance.
> I could possible try to make a pull request for a more streamlined docker-compose at some point, but we need to sort out the python part first. :)

The repeating variables in docker-compose.yml was something I tackled initially but for whatever reason I could not put it into a  docker .env file to be used. No matter what I tried, the docker-compose.yml would not read the variables defined in the docker .env file. 

If you can figure out any of these issues, I'd welcome a PR to address them and we can tackle them together.

**Comment by NoLooseEnds** [comment]
I did try this

```
  vendors:
    image: python:3
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PYTHONUSERBASE: /usr/src/vendor
    command:  >
              bash -c "python -m venv dcaenv &&
              source dcaenv/bin/activate &&
              cd /usr/src/app &&
              pip install -r requirements.txt &&
              python manage.py db init"
```

And it seems to work sort of, but that, including a bit of modified docker-compose stack crashes and exits out with:

```
vendors_1     | Traceback (most recent call last):
vendors_1     |   File "/usr/src/app/manage.py", line 3, in <module>
vendors_1     |     from project import create_app
vendors_1     |   File "/usr/src/app/project/__init__.py", line 37, in <module>
vendors_1     |     sentry_sdk.init(
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/hub.py", line 105, in _init
vendors_1     |     client = Client(*args, **kwargs)  # type: ignore
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/client.py", line 86, in __init__
vendors_1     |     self._init_impl()
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/client.py", line 108, in _init_impl
vendors_1     |     self.transport = make_transport(self.options)
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/transport.py", line 529, in make_transport
vendors_1     |     return transport_cls(options)
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/transport.py", line 142, in __init__
vendors_1     |     Transport.__init__(self, options)
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/transport.py", line 56, in __init__
vendors_1     |     self.parsed_dsn = Dsn(options["dsn"])
vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/utils.py", line 166, in __init__
vendors_1     |     raise BadDsn("Unsupported scheme %r" % parts.scheme)
vendors_1     | sentry_sdk.utils.BadDsn: Unsupported scheme ''
dcastack_vendors_1 exited with code 1
```

I don't really know what I'm doing now. Just trying to replicate the host commands in docker.

**Comment by Shazman96** [comment]
I can look into this more but it seems your error stems from Sentry sdk. Did you sign up and provide a proper sentry api key in the .env file?

**Comment by NoLooseEnds** [comment]
Yes, I think so. 

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/4103531/150871043-1f474e8b-47ad-4178-b380-b179ce09e3bd.png">

`SENTRY_KEY=62…<redacted>…92f`

What function does sentry.io have btw?

**Comment by Shazman96** [comment]
Strange, I'll have a look into building this tonight!

**Comment by Shazman96** [comment]
> What function does sentry.io have btw?

Sentry helps catch unhandled exceptions and errors. I think it's a neat tool to have to find any unexpected bugs.

**Comment by Shazman96** [comment]
> vendors:
>     image: python:latest
>     working_dir: /usr/src/app
>     volumes:
>       - ./app:/usr/src/app
>     environment:
>       PUID: ${PUID}
>       PGID: ${PGID}
>       TZ: ${TZ}
>       PYTHONUSERBASE: /usr/src/vendor
>     command:  >
>               bash -c "python -m venv dcaenv &&
>               source dcaenv/bin/activate &&
>               cd /usr/src/app &&
>               pip install -r requirements.txt &&
>               python manage.py db init"

Could you actually share your entire modified docker-compose file?

**Comment by Shazman96** [comment]
> I did try this (note that I've put the repository in /app):
> 
> ```
>   vendors:
>     image: python:latest
>     working_dir: /usr/src/app
>     volumes:
>       - ./app:/usr/src/app
>     environment:
>       PUID: ${PUID}
>       PGID: ${PGID}
>       TZ: ${TZ}
>       PYTHONUSERBASE: /usr/src/vendor
>     command:  >
>               bash -c "python -m venv dcaenv &&
>               source dcaenv/bin/activate &&
>               cd /usr/src/app &&
>               pip install -r requirements.txt &&
>               python manage.py db init"
> ```
> 
> And it seems to work sort of, but that, including a bit of modified docker-compose stack crashes and exits out with:
> 
> ```
> vendors_1     | Traceback (most recent call last):
> vendors_1     |   File "/usr/src/app/manage.py", line 3, in <module>
> vendors_1     |     from project import create_app
> vendors_1     |   File "/usr/src/app/project/__init__.py", line 37, in <module>
> vendors_1     |     sentry_sdk.init(
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/hub.py", line 105, in _init
> vendors_1     |     client = Client(*args, **kwargs)  # type: ignore
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/client.py", line 86, in __init__
> vendors_1     |     self._init_impl()
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/client.py", line 108, in _init_impl
> vendors_1     |     self.transport = make_transport(self.options)
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/transport.py", line 529, in make_transport
> vendors_1     |     return transport_cls(options)
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/transport.py", line 142, in __init__
> vendors_1     |     Transport.__init__(self, options)
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/transport.py", line 56, in __init__
> vendors_1     |     self.parsed_dsn = Dsn(options["dsn"])
> vendors_1     |   File "/usr/src/app/dcaenv/lib/python3.10/site-packages/sentry_sdk/utils.py", line 166, in __init__
> vendors_1     |     raise BadDsn("Unsupported scheme %r" % parts.scheme)
> vendors_1     | sentry_sdk.utils.BadDsn: Unsupported scheme ''
> dcastack_vendors_1 exited with code 1
> ```
> 
> I don't really know what I'm doing now. Just trying to replicate the host commands in docker.

I ran your sample code and it seemed to be working just fine on my end. Here is my docker-compose file

```
version: '3'

services:

  vendors:
    image: python:latest
    working_dir: /usr/src/project
    volumes:
      - ./project:/usr/src/project
    environment:
      PYTHONUSERBASE: /usr/src/vendor
    command:  >
              bash -c "python -m venv dcaenv &&
              source dcaenv/bin/activate &&
              cd /usr/src/project &&
              pip install -r requirements.txt &&
              python manage.py db init"

  web:
    build: .
    image: web
    container_name: web
    ports:
      - 5000:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery worker -A celery_worker.celery -f celeryLogs.log --loglevel=info --concurrency=4
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - C_FORCE_ROOT="true"
    depends_on:
      - web
      - redis

  beat:
    build: .
    command: celery -A celery_worker.celery beat
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker

  dashboard:
    build: .
    command:  flower -A celery_worker.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker

  migrations:
    build: .
    image: web
    command: >
      sh -c "python manage.py db migrate &&
             python manage.py db upgrade"
    depends_on:
      - web

  redis:
    image: redis:6-alpine
```

I will try doing a fresh clone and retry all of this.
